- name: Copy the script to usr_local_bin
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  loop:
    - "etcdctl_maintenance.sh"

- name: RUN etcdctl_maintenance.sh script
  ansible.builtin.cron:
    name: ETCD mainenance
    minute: "0"
    hour: "12"
    user: root
    job: "/usr/local/bin/etcdctl_maintenance.sh"
    cron_file: etcd_cron
  